### ISSUE TITLE
为什么感觉原型模式多此一举啊，人为增加了系统的复杂度，能分享下看法吗

### ISSUE THREAD

**Issue by haochen233** [senghoo/golang-design-pattern#12]

**Comment by senghoo** [comment]
先说一下不用原型管理器的情况。
有些时候一个函数接受的是一个接口，能对所有复合这种接口的类进行操作，但是函数内部可能需要创建同类型的对象，这种时候用的就是原型模式。比如我们有一个接口叫Person。实现接口的有Student和Teacher。 又一个函数接收Person接口的对象。对这个类做一定操作后，比如更新年纪、姓名等。然后返回修改过的新的对象，而不是修改原有对象。这种时候就需要函数内部创建新的对象。而这个对象的类型可能是不确定的（可能是Student、Teacher，或者当前不知道，以后扩充的新的类）这种时候就适合使用原型模式。这种情况Go这边用也可以用反射机制做同样的事情，思路是一样的。都是动态创建的对象。

实际使用的情景可以参考我的另一个项目当中的代码。

https://github.com/senghoo/gin-mongodb-middleware/blob/edd94495f059d5853288b5a60a355d5b5f306b28/ginm.go#L162-L177

这里我需要在每次Get方法调用的时候都需要创建一个NewBlueprint函数传进来，并且存储在结构体当中接口类型的对象的一个副本。所以用了反射机制创建了新的对象。

使用原型管理器其实是以上这种模式和工厂模式的一种配合。
