### ISSUE TITLE
想要增加一些新的设计模式

### ISSUE THREAD

**Issue by PorientHaolin** [senghoo/golang-design-pattern#22]
作者您好，您这个repo似乎只有《研磨设计模式》中提到的设计模式，我是否能增加一些其他设计模式的go实现并提交pull request呢？还是说在自己的repo中引用您的repo？

**Comment by senghoo** [comment]
这个项目的设计模式比起说是《研磨设计模式》中提到的设计模式，更多的是GoF 的 23种设计模式加一个最基础的简单工厂。
当然设计模式除了GoF的这些，根据还有很多。但是这23（或者24）种是公认的基础的模式。
为了保证项目简洁性。我希望保留现在这个状态（除非其他模式已经广泛的被认可）。

**Comment by PorientHaolin** [comment]
感谢回答
