### ISSUE TITLE
Question: did golang support decorator patten as python or java do? 

### ISSUE THREAD

**Issue by Petelin** [senghoo/golang-design-pattern#8]
比方说我们已经有了一个fib函数
https://play.golang.org/p/hYerZ2fv0dT

现在我想要在不修改源代码的前提下, 增加一个counter 装饰器

目的是统计fib调用了多少次. 因为里面有递归, 看起来go就解决不了了.

**Comment by senghoo** [comment]
有意思的问题。

golang的有些情况下抽象能力确实没有Python,Java之类的强。
但是一定程度上可以进行模仿。

我粗略的写了一个递归情况下的装饰器。确实比较繁琐，可以一起探讨一下有没有更优雅的解决方案。

https://play.golang.org/p/Tahi5nb7k9M
